GET https://api.videosdk.live/v2/rooms HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiI2YzkwZDk3OS01NThiLTRiYjctOTUyYi1hZTE0MzZiNzJmYzIiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTczMjc3MTA2NSwiZXhwIjoxNzMzMzc1ODY1fQ.KRgBInhSzrgVwUBBN0AkDzsXW4vdv8S4Ly57ZLzpfBo